### ISSUE TITLE
Saving payment method preferences without re-entering password clears the password

### ISSUE THREAD

**Issue by RohanM** [spree-contrib/spree_paypal_express#87] opened 2012-10-17 21:21 UTC
When I go to the payment method configuration page for a previously configured payment method using paypal express, and I click Update without making any other changes, the password for the payment method is set to blank. I would expect that if I didn't enter a password, the password would not be changed.

The result of this is that when, as a customer, I try to check out using paypal, when I click on the "Check Out with PayPal" or "Save and Continue" buttons on the Payment step, I receive a "Gateway Error: Security header is not valid" error.

I'm aware of a few different ways of resolving this problem. Since the preferences are handled by Spree, changing the behaviour of the password field to perform no update when the password is blank would prevent any other plugin from setting blank passwords in its settings. The field could be changed from a password to a string field, which would be suboptimal for security (although not terrible, since the admin interface uses https by default). Alternatively, we could add a hint to the field, like "Please re-enter your API password every save", or perhaps make the field required to force the user to re-enter their password.

**Comment by JDutil** [comment] 2012-10-17 21:27
This is actually just a poor user experience.  The password doesn't display within the admin configuration because it is a password input type.  The password is actually still saved, and does not get overridden when you save the configuration again unless you enter a value.  I'd like for the password field to display asterisks indicating a value is actually saved, but that would cause your password to be overridden when you save your configuration.

Your receiving the gateway error most likely because you have either entered invalid credentials or the credentials you have from Paypal do not work.  I would ensure your api credentials are correct (or try new credentials), and your logged into the developer sandbox if your running into this during development.  This is a very common issue of confusion, but is not a bug with the extension.

**Comment by RohanM** [comment] 2012-10-17 21:42
I agree that it's probably not an issue with the extension, however, I'm seeing the password being overwritten on my dev box:

```
1.9.3-p125-perf :002 > pm = Spree::PaymentMethod.find 5
1.9.3-p125-perf :003 > pm.provider
 => #<ActiveMerchant::Billing::PaypalExpressGateway:0x000000071aadb8 @options={:pem=>nil, :signature=>"*********", :headers=>{}, :currency=>"AUD", :login=>"********", :password=>"********", :review=>false, :no_shipping=>false, :allow_guest_checkout=>true, :server=>"live", :test_mode=>false}> 

# Click Update on configuration page

1.9.3-p125-perf :006 > pm = Spree::PaymentMethod.find 5
1.9.3-p125-perf :007 > pm.provider
 => #<ActiveMerchant::Billing::PaypalExpressGateway:0x00000008b2fec8 @options={:pem=>nil, :signature=>"***********", :headers=>{}, :currency=>"AUD", :login=>"************", :password=>"", :review=>false, :no_shipping=>false, :allow_guest_checkout=>true, :server=>"live", :test_mode=>false}> 
```

This is with Rails 3.2.8, Spree 1-1-stable and spree_paypal_express 1-1-stable.

**Comment by msevestre** [comment] 2012-10-17 22:02
I can confirm this issue. (I reported it at #86)
The password is being overwritten on update which is definitely a bug

**Comment by msevestre** [comment] 2012-10-17 22:04
That might be corrected with this merge
https://github.com/spree/spree/issues/2094

**Comment by RohanM** [comment] 2012-10-17 22:17
I updated spree to the latest 1-1-stable and I can confirm this is fixed. Thanks!

**Comment by JDutil** [comment] 2012-10-17 22:21
Awesome going to close this out.

**Closed as completed by JDutil** 2012-10-17 22:21 UTC
